all : strings1 fgets1 fgets2 str_shortener

strings1 : strings1.c
	gcc -o strings1 strings1.c

fgets1: fgets1.c
	gcc -o fgets1 fgets1.c

fgets2: fgets2.c
	gcc -o fgets2 fgets2.c

str_shortener: str_shortener.c
	gcc -o str_shortener str_shortener.c

clean:
	rm -f strings1
	rm -f fgets1
	rm -f fgets2
	rm -f str_shortener