all: lethead1 loccheck swap exercise6

lethead1: lethead1.c
	gcc lethead1.c -o lethead1

loccheck: loccheck.c
	gcc loccheck.c -o loccheck

swap: swap.c
	gcc swap.c -o swap

exercise6: exercise6.c
	gcc exercise6.c -o exercise6
clean:
	rm -f lethead1
	rm -f loccheck
	rm -f swap
	rm -f exercise6