all: summing scores_in exercise7
summing : summing.c
	gcc summing.c -o summing

scores_in : scores_in.c
	gcc scores_in.c -o scores_in

exercise7: exercise7.c
	gcc exercise7.c -o exercise7

clean:
	rm -f summing
	rm -f scores_in	
	rm -f exercise7